; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Auto Agent Picker"
#define MyAppVersion "1.0"
#define MyAppPublisher "wissemzidi"
#define MyAppURL "https://wissem-zidi-ofc.netlify.app"
#define MyAppExeName "Agent Auto Picker.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".setup"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{34F74956-1EBD-4E2F-A167-DBEB7A89FE50}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=D:\code\projects\auto champ (valorant) selector\src_code\LICENSE.txt
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\apps output
OutputBaseFilename=Auto Agent Picker installer
SetupIconFile=D:\code\projects\auto champ (valorant) selector\src_code\assets\icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "armenian"; MessagesFile: "compiler:Languages\Armenian.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"
Name: "bulgarian"; MessagesFile: "compiler:Languages\Bulgarian.isl"
Name: "catalan"; MessagesFile: "compiler:Languages\Catalan.isl"
Name: "corsican"; MessagesFile: "compiler:Languages\Corsican.isl"
Name: "czech"; MessagesFile: "compiler:Languages\Czech.isl"
Name: "danish"; MessagesFile: "compiler:Languages\Danish.isl"
Name: "dutch"; MessagesFile: "compiler:Languages\Dutch.isl"
Name: "finnish"; MessagesFile: "compiler:Languages\Finnish.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "hebrew"; MessagesFile: "compiler:Languages\Hebrew.isl"
Name: "hungarian"; MessagesFile: "compiler:Languages\Hungarian.isl"
Name: "icelandic"; MessagesFile: "compiler:Languages\Icelandic.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "norwegian"; MessagesFile: "compiler:Languages\Norwegian.isl"
Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "slovak"; MessagesFile: "compiler:Languages\Slovak.isl"
Name: "slovenian"; MessagesFile: "compiler:Languages\Slovenian.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"
Name: "ukrainian"; MessagesFile: "compiler:Languages\Ukrainian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\setuptools-57.0.0.dist-info\*"; DestDir: "{app}\setuptools-57.0.0.dist-info"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\ui\*"; DestDir: "{app}\ui"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\wheel-0.36.2.dist-info\*"; DestDir: "{app}\wheel-0.36.2.dist-info"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\win32\*"; DestDir: "{app}\win32"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\win32com\*"; DestDir: "{app}\win32com"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\tcl\*"; DestDir: "{app}\tcl"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\tcl8\*"; DestDir: "{app}\tcl8"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\tk\*"; DestDir: "{app}\tk"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\assets\*"; DestDir: "{app}\assets"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\cv2\*"; DestDir: "{app}\cv2"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\numpy\*"; DestDir: "{app}\numpy"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\PIL\*"; DestDir: "{app}\PIL"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\PyQt5\*"; DestDir: "{app}\PyQt5"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\Pythonwin\*"; DestDir: "{app}\PythonWin"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\pywin32_system32\*"; DestDir: "{app}\pywin32_system32"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\_asyncio.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\_bz2.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\_cffi_backend.cp311-win_amd64.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\_ctypes.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\_decimal.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\_elementtree.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\_hashlib.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\_lzma.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\_multiprocessing.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\_overlapped.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\_queue.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\_socket.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\_ssl.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\_tkinter.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\_uuid.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\base_library.zip"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\config.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\config.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\libcrypto-1_1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\libffi-8.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\libopenblas64__v0.3.21-gcc_10_3_0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\libssl-1_1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\pyexpat.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\python3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\python311.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\select.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\tcl86t.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\tk86t.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\unicodedata.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\VCRUNTIME140.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\code\projects\auto champ (valorant) selector\output\Agent Auto Picker\VCRUNTIME140_1.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

